apiVersion: v1
kind: Service
metadata:
  name: data-api
spec:
  ports:
  - port: 3009
    targetPort: 3009
  selector:
    app: data-api
  type: ClusterIP
--- 
apiVersion: v1
kind: Service
metadata:
  name: flights-api
spec:
  ports:
  - port: 3003
    targetPort: 3003
  selector:
    app: flights-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: weather-api
spec:
  ports:
  - port: 3015
    targetPort: 3015
  selector:
    app: weather-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: quakes-api
spec:
  ports:
  - port: 3012
    targetPort: 3012
  selector:
    app: quakes-api
  type: ClusterIP
